[versions]
agp = "8.13.1"
androidx-compose-android = "1.9.4"
kotlin-multiplatform = "2.2.21"
jetbrains-compose = "1.9.3"
maven-publish = "0.35.0"
androidx-activity = "1.11.0"
androidx-core-ktx = "1.17.0"
androidx-appcompat = "1.7.1"
# noinspection GradleDependency
material = "1.11.0"
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
androidx-test-espresso-core = "3.7.0"
betterandroid-ui-component = "1.0.8"
betterandroid-ui-extension = "1.0.7"
betterandroid-system-extension = "1.0.3"
betterandroid-compose-extension = "1.0.2"
betterandroid-compose-multiplatform = "0.1.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-multiplatform" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-multiplatform" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[libraries]
composeExt-material-ripple = { module = "org.jetbrains.compose.material:material-ripple", version.ref = "jetbrains-compose" }
# Use a placeholder for the android compose version
# In the project to use "androidx.compose.android.version" to obtain the version
# and use the "resolutionStrategy" to replace all the current "stable" versions
androidx-compose-android = { module = "androidx.compose.runtime:runtime-android", version.ref = "androidx-compose-android" }
betterandroid-ui-component = { module = "com.highcapable.betterandroid:ui-component", version.ref = "betterandroid-ui-component" }
betterandroid-ui-extension = { module = "com.highcapable.betterandroid:ui-extension", version.ref = "betterandroid-ui-extension" }
betterandroid-system-extension = { module = "com.highcapable.betterandroid:system-extension", version.ref = "betterandroid-system-extension" }
betterandroid-compose-extension = { module = "com.highcapable.betterandroid:compose-extension", version.ref = "betterandroid-compose-extension" }
betterandroid-compose-multiplatform = { module = "com.highcapable.betterandroid:compose-multiplatform", version.ref = "betterandroid-compose-multiplatform" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso-core" }