preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  org.jetbrains.kotlin.multiplatform:
    alias: kotlin-multiplatform
    version: 1.9.21
  org.jetbrains.compose:
    alias: jetbrains-compose
    version: 1.5.11
  com.android.application:
    alias: android-application
    version: 8.2.0
  com.android.library:
    alias: android-library
    version-ref: android-application
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.26.0

libraries:
  org.jetbrains.compose.material:
    material-ripple:
      alias: composeExt-material-ripple
      version-ref: <plugins>::jetbrains-compose
  # Use a placeholder for the alpha / beta compose version
  # In the project to use "androidx.compose.android.version" to obtain the version
  # and use the "resolutionStrategy" to replace all the current "stable" versions
  androidx.compose.runtime:
    runtime-android:
      alias: androidx-compose-android
      version: 1.6.0-alpha07
  com.highcapable.betterandroid:
    ui-component:
      version: 1.0.4
    ui-extension:
      version: 1.0.2
    system-extension:
      version: 1.0.1
    compose-extension:
      version: 1.0.2
    compose-multiplatform:
      version: 0.1.0
  androidx.activity:
    activity:
      version: 1.8.1
    activity-compose:
      version: 1.8.1
  androidx.core:
    core-ktx:
      version: 1.12.0
  androidx.appcompat:
    appcompat:
      version: 1.6.1
  com.google.android.material:
    material:
      version: 1.10.0
  androidx.test.ext:
    junit:
      version: 1.1.5
  androidx.test.espresso:
    espresso-core:
      version: 3.5.1
  junit:
    junit:
      version: 4.13.2